Refactor/quarkus
okp4/kafka-processor-cosmos-tx-proto2json pull request #33
Opened 2022-07-25 12:35 UTC by ingvaar

### This PR aims to refactor this project from a JVM processor to a native one, using [Quarkus](https://quarkus.io/).

The logic stays mostly the same, the tests are not impacted. 
This PR also introduces an error topic to aggregate all transaction that failed to unmarshal.

Parts of the project that got updated:

- [x] Dockerfile : now build a complete image running the project natively
- [x] Topology creation: now uses [Quarkus Kafka Streams](https://quarkus.io/guides/kafka-streams)
- [ ] README: updated to reflect the use of Quarkus
- [ ] Github workflows: update of the Docker build job and add a native build job

2022-07-26 08:16 UTC, amimart requested changes
Seems very good! Thanks

Just some little remarks to remove references to local maven repository

2022-07-26 08:16 UTC, amimart commented on build.gradle.kts
> +    mavenLocal()
```suggestion
```
This one is not needed 😉

2022-07-26 08:16 UTC, amimart commented on settings.gradle.kts
> +        mavenLocal()
```suggestion
```

Still not needed 😊

2022-07-26 12:17 UTC, amimart submitted a review, later dismissed
This is nice thank you!

Let's play with it 😉

2022-08-02 09:53 UTC, ccamel approved these changes

2022-08-02 12:19 UTC, amimart approved these changes

2022-08-03 12:42 UTC, merged